### ISSUE TITLE
Get Android Working Correctly

### ISSUE THREAD

**Issue by joshgreaves** [BYU-PCCL/holodeck-engine#11]
The Android hasn't been updated in a long time.
When i last tried to use it, it didn't seem to move regardless of what commands I sent.

Someone needs to take a good look into the Android and specify what exactly is wrong with it.
It probably needs further upgrading to have correct constraints on range of movement and maximum torques from each joint.

Also, its movement logic should be separated from its control scheme - see issue #9

**Comment by nickwalton** [comment]
Updated with android branch.
