### ISSUE TITLE
Support for Multi-Agent Environments

### ISSUE THREAD

**Issue by joshgreaves** [BYU-PCCL/holodeck-engine#12]
This shouldn't be too hard of a request. It will probably take more work in the Python Binding.
Currently, we are using the OpenAIGym environments interface. I don't know if they have any environments for muliple agents we could learn from?

If not, it would make sense to use the interface for single agent environments, and for multi agent environments as the environment for a list of agents, and for each agent to have an act function, and the environment to have a tick function.

**Comment by nickwalton** [comment]
Fixed in develop branch.
