### ISSUE TITLE
Crashes When Incorrect Size is Specified

### ISSUE THREAD

**Issue by joshgreaves** [BYU-PCCL/holodeck-engine#13]
The viewport is expected to be 512 x 512, so when the screen is larger we try writing pixel data to memory that isn't owned by Holodeck. There has to be a more robust way to do this that accepts variable size screens, possibly specified by Python. It may also make sense to just move away from using the viewport to capture pixels if we can get a decent alternative.

**Comment by nickwalton** [comment]
Fixed in develop branch.
