### ISSUE TITLE
Headless Rendering

### ISSUE THREAD

**Issue by joshgreaves** [BYU-PCCL/holodeck-engine#15]
A headless renderer written for UE4 would allow Holodeck to be run on a supercomputer,.

**Comment by nickwalton** [comment]
Turns out Headless Rendering has been supported since version 4.14
https://answers.unrealengine.com/questions/800917/cant-run-ue-419-on-a-headless-ubuntu-1604.html
https://docs.unrealengine.com/en-us/Support/Builds/ReleaseNotes/2016/4_14
